#!/usr/bin/env python3
"""
.ai-sync/ Sync Script — Generates platform-specific config files from shared source.

Usage:
    python .ai-sync/sync.py              # Generate all platform configs
    python .ai-sync/sync.py --check       # Check if configs are up to date
    python .ai-sync/sync.py --dry-run     # Preview what would be generated

Generated files (DO NOT EDIT directly — edit .ai-sync/ files instead):
    - AGENTS.md                          (for OpenCode / GLM-5.1)
    - .agents/rules/*.md                 (for Antigravity / Gemini)
    - .agents/workflows/*.md             (copied from .ai-sync/workflows/)

Architecture (per Antigravity official docs + empirical validation):
    - Antigravity defaults to .agents/rules/ (backward support for .agent/rules/)
    - .agents/skills/ is the universal skills folder for both platforms
    - Global rules for Antigravity live in ~/.gemini/GEMINI.md (not managed here)
"""

import hashlib
import shutil
import sys
from pathlib import Path

SYNC_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SYNC_DIR.parent

CONTEXT_FILE = SYNC_DIR / "CONTEXT.md"
RULES_FILE = SYNC_DIR / "RULES.md"
MEMORY_FILE = SYNC_DIR / "MEMORY.md"
TASKS_FILE = SYNC_DIR / "TASKS.md"
HANDOFF_FILE = SYNC_DIR / "HANDOFF.md"
OPENCODE_EXT = SYNC_DIR / "extensions" / "opencode.md"
ANTIGRAVITY_EXT = SYNC_DIR / "extensions" / "antigravity.md"
WORKFLOWS_DIR = SYNC_DIR / "workflows"

AGENTS_MD = PROJECT_ROOT / "AGENTS.md"
AGENTS_DIR = PROJECT_ROOT / ".agents"
AGENTS_RULES_DIR = AGENTS_DIR / "rules"
AGENTS_WORKFLOWS_DIR = AGENTS_DIR / "workflows"
AGENTS_RULES_SHARED = AGENTS_RULES_DIR / "project-rules.md"
AGENTS_RULES_PLATFORM = AGENTS_RULES_DIR / "platform-antigravity.md"

AUTOGEN_HEADER = "<!-- AUTO-GENERATED by .ai-sync/sync.py — DO NOT EDIT DIRECTLY -->\n<!-- Edit files in .ai-sync/ instead, then run: python .ai-sync/sync.py -->\n\n"

ANTIGRAVITY_CHAR_LIMIT = 12000


def read_file(path: Path) -> str:
    """Read file content, return empty string if not found."""
    if not path.exists():
        print(f"⚠️  Warning: {path.name} not found, skipping", file=sys.stderr)
        return ""
    return path.read_text(encoding="utf-8")


def file_hash(content: str) -> str:
    """Compute SHA256 hash of content for change detection."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


def extract_body(content: str) -> str:
    """Extract body content after the header comment block (before first ## section).

    Header format in .ai-sync/ files:
        # Title
        <blank line>
        > comment lines...
        <blank line>
        ---
        <blank line>
        ## First Real Section

    We skip everything from the first '#' line up to and including the first '---'.
    """
    lines = content.split("\n")
    seen_separator = False
    body_lines = []

    for line in lines:
        if not seen_separator:
            if line.strip() == "---":
                seen_separator = True
            continue
        body_lines.append(line)

    result = "\n".join(body_lines).strip()
    if not seen_separator and content.strip():
        print(
            f"⚠️  Warning: No '---' separator found in source file. "
            f"Entire content will be included. Add a '---' after the header.",
            file=sys.stderr,
        )
        return content.strip()
    return result


def generate_opencode_agents() -> str:
    """Generate AGENTS.md for OpenCode from .ai-sync/ source files."""
    parts = [
        AUTOGEN_HEADER,
        "# AGENTS.md — Auto-loaded rules for AI sessions\n",
    ]

    context = read_file(CONTEXT_FILE)
    if context:
        parts.append(extract_body(context))

    rules = read_file(RULES_FILE)
    if rules:
        parts.append(extract_body(rules))

    opencode_ext = read_file(OPENCODE_EXT)
    if opencode_ext:
        parts.append(extract_body(opencode_ext))

    return "\n\n".join(p for p in parts if p.strip())


def generate_antigravity_shared() -> str:
    """Generate .agents/rules/project-rules.md — shared context + rules."""
    parts = [
        AUTOGEN_HEADER,
        "# Project Rules\n",
        "> **Project Constitution for AI Agents**\n"
        "> This file governs all AI agent behavior in this repository.\n"
        "> Agents MUST read this file before any code generation.\n",
    ]

    context = read_file(CONTEXT_FILE)
    if context:
        parts.append(extract_body(context))

    rules = read_file(RULES_FILE)
    if rules:
        parts.append(extract_body(rules))

    return "\n\n".join(p for p in parts if p.strip())


def generate_antigravity_platform() -> str:
    """Generate .agents/rules/platform-antigravity.md — Antigravity-specific rules."""
    parts = [
        AUTOGEN_HEADER,
        "# Antigravity Platform Rules\n",
        "> Antigravity-specific rules appended from .ai-sync/extensions/antigravity.md.\n",
    ]

    antigravity_ext = read_file(ANTIGRAVITY_EXT)
    if antigravity_ext:
        parts.append(extract_body(antigravity_ext))

    return "\n\n".join(p for p in parts if p.strip())


def sync_workflows(dry_run: bool = False) -> list[str]:
    """Copy .ai-sync/workflows/ to .agents/workflows/."""
    synced = []
    AGENTS_WORKFLOWS_DIR.mkdir(parents=True, exist_ok=True)

    if not WORKFLOWS_DIR.exists():
        return synced

    for workflow_file in WORKFLOWS_DIR.glob("*.md"):
        target = AGENTS_WORKFLOWS_DIR / workflow_file.name
        synced.append(workflow_file.name)

        if dry_run:
            print(f"  Would copy: {workflow_file.name}")
            continue

        target_content = workflow_file.read_text(encoding="utf-8")
        if len(target_content) > ANTIGRAVITY_CHAR_LIMIT:
            print(
                f"  ❌ ERROR: {workflow_file.name} is {len(target_content)} chars — exceeds {ANTIGRAVITY_CHAR_LIMIT} char limit!"
            )
            synced.pop()
            continue
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if file_hash(target_content) == file_hash(existing):
                continue
        shutil.copy2(workflow_file, target)

    return synced


def write_output(path: Path, content: str, dry_run: bool = False, char_limit: int = 0) -> bool:
    """Write content to file. Returns True if file changed."""
    if char_limit and len(content) > char_limit:
        print(
            f"  ❌ ERROR: {path.relative_to(PROJECT_ROOT)} is {len(content)} chars — exceeds {char_limit} char limit!"
        )
        return False

    if dry_run:
        existing = read_file(path) if path.exists() else ""
        if file_hash(content) != file_hash(existing):
            print(f"  Would update: {path.relative_to(PROJECT_ROOT)}")
            return True
        else:
            print(f"  Up to date: {path.relative_to(PROJECT_ROOT)}")
            return False

    existing = read_file(path) if path.exists() else ""
    if file_hash(content) == file_hash(existing):
        return False

    path.write_text(content, encoding="utf-8")
    return True


def check_up_to_date() -> bool:
    """Check if generated files match source files. Returns True if up to date."""
    agents_content = generate_opencode_agents()
    shared_content = generate_antigravity_shared()
    platform_content = generate_antigravity_platform()

    all_ok = True

    if AGENTS_MD.exists():
        existing = read_file(AGENTS_MD)
        if file_hash(agents_content) != file_hash(existing):
            print("❌ AGENTS.md is OUT OF DATE — run: python .ai-sync/sync.py")
            all_ok = False
        else:
            print("✅ AGENTS.md is up to date")
    else:
        print("❌ AGENTS.md does not exist — run: python .ai-sync/sync.py")
        all_ok = False

    if AGENTS_RULES_SHARED.exists():
        existing = read_file(AGENTS_RULES_SHARED)
        if file_hash(shared_content) != file_hash(existing):
            print("❌ .agents/rules/project-rules.md is OUT OF DATE — run: python .ai-sync/sync.py")
            all_ok = False
        else:
            print("✅ .agents/rules/project-rules.md is up to date")
    else:
        print("❌ .agents/rules/project-rules.md does not exist — run: python .ai-sync/sync.py")
        all_ok = False

    if AGENTS_RULES_PLATFORM.exists():
        existing = read_file(AGENTS_RULES_PLATFORM)
        if file_hash(platform_content) != file_hash(existing):
            print("❌ .agents/rules/platform-antigravity.md is OUT OF DATE — run: python .ai-sync/sync.py")
            all_ok = False
        else:
            print("✅ .agents/rules/platform-antigravity.md is up to date")
    else:
        print("❌ .agents/rules/platform-antigravity.md does not exist — run: python .ai-sync/sync.py")
        all_ok = False

    if WORKFLOWS_DIR.exists():
        for workflow_file in sorted(WORKFLOWS_DIR.glob("*.md")):
            target = AGENTS_WORKFLOWS_DIR / workflow_file.name
            if not target.exists():
                print(f"❌ .agents/workflows/{workflow_file.name} does not exist — run: python .ai-sync/sync.py")
                all_ok = False
            else:
                source_content = workflow_file.read_text(encoding="utf-8")
                target_content = target.read_text(encoding="utf-8")
                if file_hash(source_content) != file_hash(target_content):
                    print(f"❌ .agents/workflows/{workflow_file.name} is OUT OF DATE — run: python .ai-sync/sync.py")
                    all_ok = False
                else:
                    print(f"✅ .agents/workflows/{workflow_file.name} is up to date")

    return all_ok


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    check_only = "--check" in args

    if check_only:
        print("Checking if generated files are up to date...\n")
        up_to_date = check_up_to_date()
        sys.exit(0 if up_to_date else 1)

    print("🔄 Syncing .ai-sync/ → platform configs...\n")

    if dry_run:
        print("📋 DRY RUN — no files will be modified\n")

    print("Generating AGENTS.md (for OpenCode)...")
    agents_content = generate_opencode_agents()
    changed = write_output(AGENTS_MD, agents_content, dry_run)
    if changed and not dry_run:
        print(f"  ✅ Updated: {AGENTS_MD.relative_to(PROJECT_ROOT)}")
    elif not changed and not dry_run:
        print(f"  ⏭️  No changes: {AGENTS_MD.relative_to(PROJECT_ROOT)}")

    print("\nGenerating .agents/rules/ (for Antigravity)...")
    AGENTS_RULES_DIR.mkdir(parents=True, exist_ok=True)

    print("  Shared rules (project-rules.md)...")
    shared_content = generate_antigravity_shared()
    changed = write_output(AGENTS_RULES_SHARED, shared_content, dry_run, char_limit=ANTIGRAVITY_CHAR_LIMIT)
    if changed and not dry_run:
        print(f"    ✅ Updated: {AGENTS_RULES_SHARED.relative_to(PROJECT_ROOT)}")
    elif not changed and not dry_run:
        print(f"    ⏭️  No changes: {AGENTS_RULES_SHARED.relative_to(PROJECT_ROOT)}")

    print("  Platform rules (platform-antigravity.md)...")
    platform_content = generate_antigravity_platform()
    changed = write_output(AGENTS_RULES_PLATFORM, platform_content, dry_run, char_limit=ANTIGRAVITY_CHAR_LIMIT)
    if changed and not dry_run:
        print(f"    ✅ Updated: {AGENTS_RULES_PLATFORM.relative_to(PROJECT_ROOT)}")
    elif not changed and not dry_run:
        print(f"    ⏭️  No changes: {AGENTS_RULES_PLATFORM.relative_to(PROJECT_ROOT)}")

    print("\nSyncing workflows...")
    synced = sync_workflows(dry_run)
    if synced and not dry_run:
        print(f"  ✅ Copied {len(synced)} workflows: {', '.join(synced)}")
    elif not synced:
        print("  ⏭️  No workflows to sync")
    elif dry_run and synced:
        print(f"  Would copy {len(synced)} workflows")

    print(f"\n{'📋 DRY RUN complete' if dry_run else '✅ Sync complete'}!")
    if not dry_run:
        print("  AGENTS.md → OpenCode auto-loads this file")
        print("  .agents/rules/project-rules.md → Antigravity shared rules (Always On)")
        print("  .agents/rules/platform-antigravity.md → Antigravity platform rules (Always On)")
        print("  .agents/workflows/ → Copied from .ai-sync/workflows/")
        print("  .agents/skills/ → Universal skills (managed separately)")
        print("\n⚠️  Remember: NEVER edit generated files directly. Edit .ai-sync/ files instead.")


if __name__ == "__main__":
    main()
